// sidebars.js — TPP section
// Paste the 'tppsSidebar' key into your existing sidebars.js,
// or merge the category block into your main sidebar array.

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {

  // Option A: standalone sidebar (register in docusaurus.config.js)
  tppsSidebar: [
    {
      type: 'autogenerated',
      dirName: 'tpps',
    },
  ],

  // Option B: category block to paste into your existing sidebar array
  // mainSidebar: [
  //   // ... your existing entries ...
  //   {
  //     type: 'category',
  //     label: 'TPP Privacy Badges',
  //     collapsed: true,
  //     link: { type: 'doc', id: 'tpps/index' },
  //     items: [{ type: 'autogenerated', dirName: 'tpps' }],
  //   },
  // ],
};

module.exports = sidebars;
